version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
